config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    root "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end  
  end

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
  	resources :tickets
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end  

  resources :attachments, only: [:show, :new]	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :ticket

  mount_uploader :file, AttachmentUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :state
  belongs_to :ticket
  belongs_to :author, class_name: "User"

  validates :text, presence: true

  delegate :project, to: :ticket

  scope :persisted, lambda { where.not(id: nil) }

  after_create :set_ticket_state

  private

  def set_ticket_state
    ticket.state = state
    ticket.save!
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tickets, dependent: :destroy
	has_many :roles, dependent: :delete_all

  	validates :name, presence: true
  	validates :description, presence: true

  	def has_member?(user)
  		roles.exists?(user_id: user)
  	end

  	[:manager, :editor, :viewer].each do |role|
  		define_method "has_#{role}?" do |user|
  			roles.exists?(user_id: user, role: role)
  		end
  	end		
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :project

  def self.available_roles
    %w(manager editor viewer)
  end
end

app/models/state.rb
class State < ApplicationRecord
  def to_s
    name
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :author, class_name: "User"
  belongs_to :state
  has_many :attachments, dependent: :destroy
  has_many :comments, dependent: :destroy

  
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 1 }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :roles

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :excluding_archived, lambda { where(archived_at: nil) }       

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit

	after_action :verify_authorized, except: [:index],
		unless: :devise_controller?
	after_action :verify_policy_scoped, only: [:index],
		unless: :devise_controller?

	rescue_from Pundit::NotAuthorizedError, with: :not_authorized

	private

	def not_authorized
		redirect_to root_path, alert: "ACCESS DENIED."
	end	

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
	skip_after_action :verify_authorized, only: [:new]

  def show
  	attachment = Attachment.find(params[:id])
  	authorize attachment, :show?
  	send_file attachment.file.path, disposition: :inline
  end


  def new
  	@index = params[:index].to_i
  	@ticket = Ticket.new
  	@ticket.attachments.build
  	render layout: false
  end	

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_ticket

  def create
    @comment = @ticket.comments.build(comment_params)
    @comment.author = current_user
    authorize @comment, :create?

    if @comment.save
      flash[:notice] = "Comment has been created."
      redirect_to [@ticket.project, @ticket]
    else
      flash.now[:alert] = "Comment has not been created."
      @project = @ticket.project
      render "tickets/show"
    end
  end

private

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :state_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update]
	
	def index
		@projects = policy_scope(Project)
	end

	def show
	    authorize @project, :show?
	    @tickets = @project.tickets
    end

	def edit
		authorize @project, :update?
	end

	def update
	    authorize @project, :update?
	    if @project.update(project_params)
	      flash[:notice] = "Project has been updated."
	      redirect_to @project
	    else
	      flash.now[:alert] = "Project has not been updated."
	      render "edit"
	    end
  	end

	private

	def set_project
		  @project = Project.find(params[:id])
		rescue ActiveRecord::RecordNotFound
		  flash[:alert] = "The project you were looking for could not be found."
		  redirect_to projects_path
	end	

	def project_params
		params.require(:project).permit(:name, :description)
	end		
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :watch]

	def new
  		@ticket = @project.tickets.build
      authorize @ticket, :create?
      @ticket.attachments.build
	end


	def create
  		@ticket = @project.tickets.build(ticket_params)
      @ticket.author = current_user
      authorize @ticket, :create?

  			if @ticket.save
    			flash[:notice] = "Ticket has been created."
    			redirect_to [@project, @ticket]
  			else
    			flash.now[:alert] = "Ticket has not been created."
    			render "new"
  			end
	end

  def show
    authorize @ticket, :show?
    @comment = @ticket.comments.build
  end

  def edit
    authorize @ticket, :update?
  end
  
  def update
    authorize @ticket, :update?
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
      authorize @ticket, :destroy?
      @ticket.destroy
      flash[:notice] = "Ticket has been deleted."

      redirect_to @project
  end 

	private

	def ticket_params
  		params.require(:ticket).permit(:name, :description, attachments_attributes: [:file, :file_cache])
	end

  def set_project
    	@project = Project.find(params[:project_id])
  end

  def set_ticket
      @ticket = @project.tickets.find(params[:id])
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Ticketee").join(" - ")
			end
		end
	end

	def admins_only(&block)
    	block.call if current_user.try(:admin?)
  	end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield(:title) %>
      <% else %>
          Ticketee
      <% end %>      
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Ticketee", root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page?("/") %>">
          <%= link_to "Home", root_path %>
        </li>
        <% admins_only do %>
          <li>
            <%= link_to "Admin", admin_root_path %>
          </li>
        <% end %>
       <% unless user_signed_in? %> 
        <li class="<%= "active" if current_page?("/users/sign_up") %> ">
            <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li class="<%= "active" if current_page?("/users/sign_in") %>">
            <%= link_to "Sign in", new_user_session_path %>
        </li>
       <% end %> 
      </ul>
      <% if user_signed_in? %>
              <div class="navbar-right">
                <p class="navbar-text">
                  Signed in as <%= current_user.email %>
                </p>
                <ul class="nav navbar-nav">
                  <li><%= link_to "Sign out", destroy_user_session_path,
              method: :delete %>
                  </li>
                </ul>
              </div>
      <% end %>
    </div>
  </div>
</nav>

  <body>
    <div class="container">
      <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %>">
            <%= message %>
          </div>
      <% end %>  

      <%= yield %>
    </div>
  </body>
</html>